DELETE FROM Orders;
DELETE FROM Schedules;
DELETE FROM Users;
DELETE FROM Roles;
DELETE FROM Movies;
DELETE FROM Halls;

ALTER TABLE Orders MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE Schedules MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE Users MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE Roles MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE Movies MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE Halls MODIFY Id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

COMMIT;

INSERT INTO Roles (Name) VALUES ('Пользователь');
INSERT INTO Roles (Name) VALUES ('Менеджер');
INSERT INTO Roles (Name) VALUES ('Администратор');
COMMIT;

INSERT INTO Users (Name, Surname, Email, Password, RoleId)
VALUES (
    'Главный',
    'Администратор',
    'admin@cinema.com', 
    'AdminPassword123', 
    (SELECT Id FROM Roles WHERE Name = 'Администратор')
);
COMMIT;

INSERT INTO Users (Name, Surname, Email, Password, RoleId)
VALUES (
    'Первый',
    'Менеджер',
    'manager@cinema.com', 
    'ManagerPassword123', 
    (SELECT Id FROM Roles WHERE Name = 'Менеджер')
);
COMMIT;