CREATE USER C##CinemaAdmin IDENTIFIED BY CinemaAdmin123;
GRANT CONNECT, RESOURCE, DBA TO C##CinemaAdmin CONTAINER=ALL;

CREATE USER C##CinemaManager IDENTIFIED BY CinemaManager123;
GRANT CONNECT TO C##CinemaManager CONTAINER=ALL;

CREATE USER C##CinemaClient IDENTIFIED BY CinemaClient123;
GRANT CONNECT TO C##CinemaClient CONTAINER=ALL;