SET SERVEROUTPUT ON;

CREATE OR REPLACE PUBLIC SYNONYM Roles FOR C##CinemaAdmin.Roles;
CREATE OR REPLACE PUBLIC SYNONYM Users FOR C##CinemaAdmin.Users;
CREATE OR REPLACE PUBLIC SYNONYM Movies FOR C##CinemaAdmin.Movies;
CREATE OR REPLACE PUBLIC SYNONYM Halls FOR C##CinemaAdmin.Halls;
CREATE OR REPLACE PUBLIC SYNONYM Schedules FOR C##CinemaAdmin.Schedules;
CREATE OR REPLACE PUBLIC SYNONYM Orders FOR C##CinemaAdmin.Orders;

CREATE OR REPLACE PUBLIC SYNONYM ADMIN_PKG FOR C##CinemaAdmin.ADMIN_PKG;
CREATE OR REPLACE PUBLIC SYNONYM MANAGER_PKG FOR C##CinemaAdmin.MANAGER_PKG;
CREATE OR REPLACE PUBLIC SYNONYM CLIENT_PKG FOR C##CinemaAdmin.CLIENT_PKG;

GRANT EXECUTE ON CLIENT_PKG TO C##CinemaClient;

GRANT EXECUTE ON CLIENT_PKG TO C##CinemaManager;
GRANT EXECUTE ON MANAGER_PKG TO C##CinemaManager;

GRANT EXECUTE ON CLIENT_PKG TO C##CinemaAdmin;
GRANT EXECUTE ON MANAGER_PKG TO C##CinemaAdmin;
GRANT EXECUTE ON ADMIN_PKG TO C##CinemaAdmin;

GRANT SELECT ON Roles TO C##CinemaManager;
GRANT SELECT ON Users TO C##CinemaManager;
GRANT SELECT ON Movies TO C##CinemaManager;
GRANT SELECT ON Halls TO C##CinemaManager;
GRANT SELECT ON Schedules TO C##CinemaManager;
GRANT SELECT ON Orders TO C##CinemaManager;