CREATE PLUGGABLE DATABASE CINEMAPDB
ADMIN USER CinemaPDBAdmin IDENTIFIED BY CinemaAdminPassword123
ROLES = (DBA)
FILE_NAME_CONVERT = ('/opt/oracle/oradata/XE/pdbseed/', '/opt/oracle/oradata/XE/CINEMAPDB/');

ALTER PLUGGABLE DATABASE CINEMAPDB OPEN;

ALTER PLUGGABLE DATABASE CINEMAPDB SAVE STATE;
