BEGIN EXECUTE IMMEDIATE 'DROP DIRECTORY MEDIA_DIR';
    EXCEPTION WHEN OTHERS THEN NULL; 
END;
/

CREATE OR REPLACE DIRECTORY MEDIA_DIR AS '/media';

GRANT READ, WRITE ON DIRECTORY MEDIA_DIR TO C##CinemaAdmin;
GRANT READ, WRITE ON DIRECTORY MEDIA_DIR TO C##CinemaManager;

SELECT directory_path FROM all_directories WHERE directory_name = 'MEDIA_DIR';